export const INIT = 'COMMON/INIT';
export const RELOAD = 'COMMON/RELOAD';
export const SEND_TO_SF = 'COMMON/SEND_TO_SF';
export const SEND_TO_LISTER = 'COMMON/SEND_TO_LISTER';
export const SEND_TO_LISTER_READY_EVENT_SG = 'SEND_TO_LISTER_READY_EVENT_SG';

export const RE_INIT = 'COMMON/RE_INIT';
export const TOGGLE_PROCESSING = 'COMMON/TOGGLE_PROCESSING';
