export const ACTIVE_URL_CHANGED = 'CHROME/ACTIVE_URL_CHANGED';
export const ADD_CHROME_EVENTS_LISTENERS = 'CHROME/ADD_CHROME_EVENTS_LISTENERS';
export const AVAILABLE_UPDATE = 'CHROME/AVAILABLE_UPDATE';
