// export const ACTIVE_URL_CHANGED = 'BROWSER/ACTIVE_URL_CHANGED';
// export const ADD_BROWSER_EVENTS_LISTENERS = 'BROWSER/ADD_BROWSER_EVENTS_LISTENERS';
// export const AVAILABLE_UPDATE = 'BROWSER/AVAILABLE_UPDATE';
